on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: "docker login"
        run: docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}

      - name: "building docker image"
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/daliayasser .

      - name: "pushing to docker hub"
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/daliayasser